language: node_js
sudo: required
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
  - "10"
addons:
  postgresql: "9.6"
script: "npm run travis"
before_script:
  - psql -c 'create database pg_promise_test;' -U postgres
  - node test/db/init.js
env:
  - BLUEBIRD_DEBUG=0
